name = "MaximumLikelihoodProblems"
uuid = "e149cee4-a9c8-4a03-a7b6-d91720412337"
authors = ["Dilum Aluthge"]
version = "0.1.0-DEV"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
